### ISSUE TITLE
How to manage a List of Posts

### ISSUE THREAD

**Issue by mrbarletta** [Youshido/GraphQL#1]
In the examples  ListType is used with interfaces
But what if I want a list of posts? How do you handle that? 

Tried as ListType ( new PostType()) and returned an array of posts and it didn't work.

Thanks!

PS: Thanks for the awesome work ! tried many tools and this one was the best php helper/library I found, very well documented. I just made a PR to the awesome list for PHP related projects: 
https://github.com/chentsulin/awesome-graphql/pull/71 #71

**Comment by portey** [comment]
Hi, @mrbarletta 
thank you for your question!

There are two ways how to use ListType:

1. For inline style, you must pass resolver function and array of arguments (if you needed) to ListType:
 ```php
new ListType(new SomeType(), [
    'resolve' => function($value = null, $args = [], $type) {
       //here return array or iterator
    },
    'args' => [
       'limit' => [ 'type' => TypeMap::TYPE_INT ],
       'offset' => ['type' => TypeMap::TYPE_INT ]
    ]
])
```

2. For OOP style you need to extend AbstractListType:
 ```php
class PostListType extends AbstractListType
{

    public function getItemType()
    {
        return new PostType();
    }

    public function build($config)
    {
        $config
            ->addArgument('limit', new NonNullType(TYPE_MAP::TYPE_INT))
            ->addArgument('offset', new NonNullType(TYPE_MAP::TYPE_INT));
    }

    public function resolve($value = null, $args = [], $type = null)
    {
        //return array
    }

}
 ```

**Comment by mrbarletta** [comment]
Awesome - I managed to use it just fine! thanks a lot

For reference, to make it work TYPE_MAP has to be camelcased TypeMap.  
```
$config
->addArgument('limit', new NonNullType(TypeMap::TYPE_INT))
->addArgument('offset', new NonNullType(TypeMap::TYPE_INT));
```

**Comment by viniychuk** [comment]
Thanks @mrbarletta , we updated the previous comment.
