### ISSUE TITLE
Requesting undefined subfield results in a fatal error

### ISSUE THREAD

**Issue by Zombaya** [Youshido/GraphQL#10]
If you request a subfield which is not defined, you get a fatal error.

## Example-query

	{Test{
	  name,
	  bla {
	  }
	}}

The test-type only has the field _name_ defined.  The subfield _bla_ is never defined which causes the fatal error.

## Testfiles
[testfiles.zip](https://github.com/Youshido/GraphQL/files/356896/testfiles.zip)

## Stacktrace
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught TypeError: Argument 2 passed to Youshido\GraphQL\Execution\Processor::processQueryAST() must be an instance of Youshido\GraphQL\Field\AbstractField, null given, called in /home/pieter/workfiles/sigura-industries/vendor/youshido/graphql/src/Execution/Processor.php on line 332 and defined in /home/pieter/workfiles/sigura-industries/vendor/youshido/graphql/src/Execution/Processor.php on line <i>127</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> TypeError: Argument 2 passed to Youshido\GraphQL\Execution\Processor::processQueryAST() must be an instance of Youshido\GraphQL\Field\AbstractField, null given, called in /home/pieter/workfiles/sigura-industries/vendor/youshido/graphql/src/Execution/Processor.php on line 332 in /home/pieter/workfiles/sigura-industries/vendor/youshido/graphql/src/Execution/Processor.php on line <i>127</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>384928</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/pieter/workfiles/sigura-industries/graphql.php' bgcolor='#eeeeec'>.../graphql.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0089</td><td bgcolor='#eeeeec' align='right'>706880</td><td bgcolor='#eeeeec'>Sigura\Mods\Industries\Graphql->__construct(  )</td><td title='/home/pieter/workfiles/sigura-industries/graphql.php' bgcolor='#eeeeec'>.../graphql.php<b>:</b>8</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.1232</td><td bgcolor='#eeeeec' align='right'>2184024</td><td bgcolor='#eeeeec'>Youshido\GraphQL\Execution\Processor->processPayload(  )</td><td title='/home/pieter/workfiles/sigura-industries/classes/mods.industries/_namespaced/Graphql.class.php' bgcolor='#eeeeec'>.../Graphql.class.php<b>:</b>122</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.1248</td><td bgcolor='#eeeeec' align='right'>2253088</td><td bgcolor='#eeeeec'>Youshido\GraphQL\Execution\Processor->executeOperation(  )</td><td title='/home/pieter/workfiles/sigura-industries/vendor/youshido/graphql/src/Execution/Processor.php' bgcolor='#eeeeec'>.../Processor.php<b>:</b>76</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.1249</td><td bgcolor='#eeeeec' align='right'>2270560</td><td bgcolor='#eeeeec'>Youshido\GraphQL\Execution\Processor->processQueryAST(  )</td><td title='/home/pieter/workfiles/sigura-industries/vendor/youshido/graphql/src/Execution/Processor.php' bgcolor='#eeeeec'>.../Processor.php<b>:</b>118</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.1251</td><td bgcolor='#eeeeec' align='right'>2395400</td><td bgcolor='#eeeeec'>Youshido\GraphQL\Execution\Processor->collectValueForQueryWithType(  )</td><td title='/home/pieter/workfiles/sigura-industries/vendor/youshido/graphql/src/Execution/Processor.php' bgcolor='#eeeeec'>.../Processor.php<b>:</b>135</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.1252</td><td bgcolor='#eeeeec' align='right'>2398864</td><td bgcolor='#eeeeec'>Youshido\GraphQL\Execution\Processor->processQueryFields(  )</td><td title='/home/pieter/workfiles/sigura-industries/vendor/youshido/graphql/src/Execution/Processor.php' bgcolor='#eeeeec'>.../Processor.php<b>:</b>171</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>0.1254</td><td bgcolor='#eeeeec' align='right'>2424840</td><td bgcolor='#eeeeec'>Youshido\GraphQL\Execution\Processor->processQueryAST(  )</td><td title='/home/pieter/workfiles/sigura-industries/vendor/youshido/graphql/src/Execution/Processor.php' bgcolor='#eeeeec'>.../Processor.php<b>:</b>332</td></tr>
</table></font>

**Comment by viniychuk** [comment]
@Zombaya thanks for reporting the problem, we'll get it fixed asap.

**Comment by viniychuk** [comment]
this got fixed in the latest release - v1.1.4
