### ISSUE TITLE
Allow an InputObject with NonNullable fields to be null

### ISSUE THREAD

**Issue by Zombaya** [Youshido/GraphQL#104]
I'm having trouble with setting an InputObject to null if it has a field that is not nullable.

In the test author is an inputobject with a nonnullable field name, but author itself is nullable.
````
CreateAuthor()              => works
CreateAuthor(author:null)   => does not work, but should work in my opinion
````

I created a test for this and this is in pull-request #103.

**Comment by viniychuk** [comment]
@Zombaya fixed in 1.4.2.9
