### ISSUE TITLE
Feature: allow access to child fields

### ISSUE THREAD

**Issue by svrcekmichal** [Youshido/GraphQL#105]
It would be awesome if field would contain child fields. For example in query

```
users {
  edges {
    node {
       id
       location
    }
  }
}
```
I can only access `edges` field but it would be awesome if `Field` would have function for example `getChildFields` which would return `FieldList`. `FieldList` is something new too. It can have methods like `getFieldByName` or `hasField` to simplify access of fields

**Comment by viniychuk** [comment]
@svrcekmichal I added example to the Test109Schema resolve function, but now you can do:
`$info->getFieldAST('node')`, `$astField->getArgument('id')`, `$info->getFieldAST('comments')->getFields()` and all other things that are needed for going over the request.
