### ISSUE TITLE
Should clearErrors() be called at the beginning of processPayload? 

### ISSUE THREAD

**Issue by brunoreis** [Youshido/GraphQL#106]
Hi, I'm not sure if it's an error. but I am calling processPayload more than once and it has a bad behaviour (IMHO) when an error occurs. If an error occurs and I call processPayload again that error will stick there and the second call will have that error on the response. 

The errors are being kept there (by the ErrorContainerTrait) and are not cleaned between two calls.

I was able to "fix" it like this: 

```
$processor = $this->getService('graphql.processor');
$processor->getExecutionContext()->clearErrors();
$processor->processPayload($query);
return $processor->getResponseData();
```

But I think that you could call the clean errors on every processPayload call. At least this is what I can tell from my actual understanding of the API. In the case that a new processor should be created for every "request", so this might be an issue with the symfony bundle, that should declare the processor service with shared:false.

**Comment by viniychuk** [comment]
@brunoreis Originally it was exactly like you described, but then, we realized that there are not a lot of situation where people need to run processor->processPayload multiple times, and when they do – they better do something about their errors explicitly... so we made a change. Unless you're using the reactPHP so you have some sort of run-loop – then you're absolutely right, but in that case you can definitely clear errors manually.

**Comment by viniychuk** [comment]
@brunoreis just curios, can you share your case, how exactly are you using it so you have to call processPayload more then one time during the one request?

**Comment by Schunk** [comment]
I noticed the same thing, here is my use case:
I use a proxy controller on top of my graphql queries (stored in database), and I forward each query to the Youshido controller.
I can forward several queries or mutations per master request, but in that case the errors I receive are not cleared.

**Comment by brunoreis** [comment]
@viniychuk, I decided to make my integration test making graphql calls, using the graphql layer. So I call a lot of queries and mutations in a single test.

**Comment by fritz-gerneth** [comment]
@brunoreis I think for better test isolation each test should have its own `Processor` in this case (e.g. created in the `setUp` method or alike). This way you can be sure to not have any side-effects from previous runs. This is not limited to errors but potential other parts as well (like caching ....)

**Comment by brunoreis** [comment]
I have multiple calls even in the same test. I'm clearing erros, but I
noticed that sometimes I needed to do an entityManager->clear also. I have
not noticed anything between tests. I'm not sure if the container creates a
new instance per test, but I imagine it does. Thanks.

2017-01-21 15:52 GMT-02:00 Fritz Gerneth <notifications@github.com>:

**Comment by viniychuk** [comment]
@brunoreis , @fritz-gerneth , @Schunk If you were to choose, which way would you prefer?

1. Automatically clear errors **at the beginning** of the `processPayload`
2. Add a parameter to `getResponseData($clearErrors = true)`
3. Not a big deal, we can leave it as is

The reason I wanted to have it as it is right now is for the shared processor use. From my point of view – you can always clear errors if you need to, but you cannot restore them if library is cleaning them automatically :)

**Comment by brunoreis** [comment]
3

Em 5 de fev de 2017 2:57 PM, "Alexandr Viniychuk" <notifications@github.com>
escreveu:

**Comment by fritz-gerneth** [comment]
In this order: 3,1,2

In my oppinion the `getResponseData` should only do this one job without side-effects (functions should not do two things). If at all, it'd actually more see it of a job of `processPayload` to prepare & clean up the context (for option 1). 
In the end I think when invoked in a re-usable context it should be the loop's job to clean this up (favor for option 3).

**Comment by viniychuk** [comment]
Ok guys, thanks all for commenting, will close it for now.
