### ISSUE TITLE
Add explicit setters for core properties of Config Objects

### ISSUE THREAD

**Issue by fritz-gerneth** [Youshido/GraphQL#108]
It would be a nice addition to have explicit setters for the used config properties for the different types of config objects that are passed to their respective `build` method. 

So instead of calling `set('description', 'my description')` we'd have the function `setDescription` defined explicitly. I'm aware of the magic `_set` to achieve this already but this throws of any analyzer / IDE that this function is not defined. Internally this function simply would call `set` with the respective config key. While at it, it probably would be convenient to have getters for those as well. 

Pros:
- IDE support to know which properties can be used in the current context
- No magic string configuration (hide the fact that the description is stored in a key string)
- No BC break

Willing to add those if this seems like a decent addition :)

**Comment by viniychuk** [comment]
@fritz-gerneth In fact we just need to add PHPDOC comments to the class definition to allow autocomplete and IDE support. I added one for description in `v1.4.2.1` so you can see if it works for you
