### ISSUE TITLE
Arguments in nested fields trigger an error

### ISSUE THREAD

**Issue by Schunk** [Youshido/GraphQL#116]
Hi, when I use an argument in my query in nested fields like this:
```graphql
query ($size: Int) {
  connections(first: 0) {
    pageInfo {
      totalEdges
      cursors (size: $size)
    }
}
```
I got this error:
```
Error: Call to a member function getType() on null
at vendor\youshido\graphql\src\Execution\Processor.php:499
```

Is it allowed? I use the YoushidoBundle with Symfony, and the error occurs when parsing the arguments at the beginning of `doResolve`: `$arguments = $this->parseArgumentsValues($field, $ast);`

**Comment by viniychuk** [comment]
@Schunk thanks for reporting the issue, will get it resolved this weekend, although it seems like it was already fixed
