### ISSUE TITLE
Using a class that extends AbstractField as a field in an AbstractType is throwing an error.

### ISSUE THREAD

**Issue by chasen** [Youshido/GraphQL#118]
I am using version v1.4.2.14.

I am trying to accomplish the following:
```
query { 
   articleSummary(id:1) {
       title,
       body,
       article {
          id
       }
   }
}
```

I have an ArticleSummaryField.php:

```
class ArticleSummaryField extends AbstractField
{
    public function build(FieldConfig $config)
    {
        $config->addArgument('id', new NonNullType(new StringType()));
    }

    public function getType()
    {

        return new ArticleSummaryType();
    }

    public function resolve($value, array $args, ResolveInfo $info)
    {
        return [
            'title' => 'test title',
            'body' => 'test body',
            'article' => $args['id']
        ];
    }
}
```

Then the ArticleSummaryType.php:
```
class ArticleSummaryType extends AbstractObjectType
{
    public function build($config)
    {
        $config
            ->addField('title', new StringType());
            ->addField('body', new StringType());
            ->addField('article', new ArticleField());
    }
}
```

Then the ArticleField.php has the getType method return the ArticleType which has the `id` field.

However what i am getting is an error: 

```
Fatal error: Uncaught Error: Call to undefined method ArticleField::getNullableType() in .../vendor/youshido/graphql/src/Execution/Processor.php on line 135
```

What seems to be happening is that when `$targetField->getType()` on line 135 in src/Execution/Processor.php is called its returning the `ArticleField` class, not the `ArticleType` class.

I would expect that to return the class as declared in the 'getType' method on the ArticleField class.

Am i going about this wrong for nesting fields? Or is there a bug in the library?

**Comment by viniychuk** [comment]
@chasen you should update your `ArticleSummaryType.php`:

```
class ArticleSummaryType extends AbstractObjectType
{
    public function build($config)
    {
        $config
            ->addField('title', new StringType());
            ->addField('body', new StringType());
            ->addField(new ArticleField());
    }
}
```

But I'd suggest using a shorter syntax:
```
class ArticleSummaryType extends AbstractObjectType
{
    public function build($config)
    {
        $config->addFields([
            'title' => new StringType(),
            'body'  => new StringType(),
            new ArticleField(),
        ]);
    }
}
```

**Comment by chasen** [comment]
Aw perfect! thank you for the fast response!

**Comment by chasen** [comment]
@viniychuk Follow up question, how would I accomplish nesting a FieldClass in a a list type?

```
$config->addFields([
    'title' => new StringType(),
    'body'  => new StringType(),
    'relatedArticles' => new ListType(new ArticleField()),
]);
```

Fatal error: Uncaught Error: Call to undefined method ArticleField::isInputType() in .../vendor/youshido/graphql/src/Type/ListType/AbstractListType.php on line 38

**Comment by viniychuk** [comment]
@chasen Sure, just so you know, there's no such thing as a list of fields :)

So you should have a type which is a list of other types. And to do so:
```php
$config->addFields([
    'title' => new StringType(),
    'body'  => new StringType(),
    'relatedArticles' => new ListType(new ArticleType()),
]);
```

Or you can create a field of related articles (wouldn't recommend unless you can reuse it somewhere):
```php
$config->addFields([
    'title' => new StringType(),
    'body'  => new StringType(),
    new RelatedArticlesField()
]);
```

Or you can create an `ArticlesList` type by extending `AbstractListType` (also don't see a reason, unless your project is about articles and you will be using that type a lot)

**Comment by chasen** [comment]
The problem that i have is that i need to have access to a Resolve function on the Article. But i think i have a solution, create an ArticleListField that will return the ListType(new ArticleType()), that will handle the resolution of those.
