### ISSUE TITLE
variables in nested fields and queries don't work

### ISSUE THREAD

**Issue by roippi** [Youshido/GraphQL#12]
This works fine:
```
{ foo { bar(value:"baz") } }
```

But the following equivalent query with provided variables `{value:"baz"}` bombs out:
```
query nestedQuery($value:String!){
  foo {
    bar(value:$value)
}
```

Error message is somewhat opaque: `"Value not set to variable else"`

I've provided a regression test here: https://github.com/roippi/GraphQL/commit/54f310bde9ec0e622e78a6000b7f3b95728eb466

The fix is non-trivial so I don't know if/when I'll have a pull request available.  I've traced through it and it looks like `$this->resolveValidator->validateArguments` is only getting invoked at the operation level, not at the individual field level.

Thanks for the awesome library.

**Comment by viniychuk** [comment]
Thanks for your input, I'll look into it tomorrow as well.

**Comment by viniychuk** [comment]
Hi, @roippi I got it fixed and published new version v1.1.4.1. Please, check if it works for you when you have time, thanks!

**Comment by roippi** [comment]
Hi @viniychuk thanks for the quick response!

Looks like your patch fixed some of the issues I was seeing (and made my test pass)

Unfortunately there's a different issue with nested Queries that have resolveFuncs attached to them.  I've submitted a pull request with a regression test and a fix, hope it helps.

**Comment by viniychuk** [comment]
Thanks @roippi, I appreciate your help 👍 . Your fix is good but I'll need to make some other small changes. I'd ask you next time please create a separate pull request for the non-working test specifically, and a pull request for the fix after that. In that way I will be able to get your test without merging a fix in case fix could be written a bit different.
Again, thanks for spending time making this better!

**Comment by roippi** [comment]
You got it. Thanks.
