### ISSUE TITLE
Use ISO format for DateTimeType

### ISSUE THREAD

**Issue by fesor** [Youshido/GraphQL#124]
Currently `DateTimeType` uses `Y-m-d H:i:s` instead of ISO 8601. From compatibility point of view this format is not preferable.

I know that this could be potentially BC break but maybe in future releases.

**Comment by fritz-gerneth** [comment]
The `DateTimeType` has an optional parameter `format` you can use to specify the format you want the date formated to:

```
class MyCustomType extends AbstractObjectType
{
    public function build($config)
    {
        $config
            ->addField('id', new IdType())
            ->addField('createdAt', new DateTimeType('c')); // Prints date in ISO 8601: 2004-02-12T15:19:21+00:00
    }
}
```
Format follow the one accepted by the [date](http://php.net/manual/de/function.date.php) function.

**Comment by viniychuk** [comment]
@fesor It's going to be changed in 2.0 I guess, but we're going to keep the old one in the current brunch.
@fritz-gerneth thanks for replying here!
