### ISSUE TITLE
query fields

### ISSUE THREAD

**Issue by lhyx** [Youshido/GraphQL#125]
Hi,

Is it possible to get a list of the fields that where requested in a query ?

For example:

{Query{field1, field2, field3}}

How can I get an array containing field1, field2, field3 ?

In the resolve function in a query there seems to be an argument info but it is always empty.

Thanks in advance.

**Comment by Schunk** [comment]
You can use the argument `$info` in your resolve function to get a flat list of the queried fields:

```php
public function resolve($value, array $args, ResolveInfo $info)
{
    $fields = $info->getFieldASTList();
}
```
