### ISSUE TITLE
Trailing commas not allowed

### ISSUE THREAD

**Issue by bdchauvette** [Youshido/GraphQL#128]
Thanks for a great library! 😃

While playing around with this library today, I noticed that it returns an `Unexpected token \"RBRACE\"` error when it encounters a trailing comma, e.g.

```graphql
{
  foo,
  bar,
  baz,
}
```

However, the GraphQL spec ([&sect;2.1.5](https://facebook.github.io/graphql/#sec-Insignificant-Commas)) says that all commas should be insignificant, and trailing commas should be allowed.

I put together a gist to the issue: https://gist.github.com/bdchauvette/e84b9ff1925e58950a339783b8d093ae

**Comment by akomm** [comment]
Actually, even something like that should work:

```
{
  foo,   , , , , , , ,
  bar
  baz
}
```
[§2.1.7](https://facebook.github.io/graphql/#sec-Source-Text.Ignored-Tokens) Quote:
`Before and after every lexical token may be any amount of ignored tokens including [...]`
