### ISSUE TITLE
InlinedTypeFragments allow invalid types without errors

### ISSUE THREAD

**Issue by fritz-gerneth** [Youshido/GraphQL#130]
Typed inline fragments referencing an invalid type are silently ignored. Following the reference [implementation & example ](http://graphql.org/learn/queries/#inline-fragments) passing an invalid type should return an error instead. 

On the reference implementation, executing a query like this:
```
query HeroForEpisode($ep: Episode!) {
  hero(episode: $ep) {
    name
    ... on InvalidTypeName {
      primaryFunction
    }
    ... on Human {
      height
    }
  }
}
```
returns the error
```
{
  "errors": [
    {
      "message": "Unknown type \"InvalidTypeName\". Did you mean \"Droid\"?",
      "locations": [
        {
          "line": 4,
          "column": 12
        }
      ]
    }
  ]
}
```

On the current implementation here, there is no error returned but only the fields of the base interfaces are returned (i.e. the fragment is simply ignored).

**Comment by portey** [comment]
done, merged to v2.0 (wait for release)
