### ISSUE TITLE
Variable Validation Fails - mutation with a List of Input types

### ISSUE THREAD

**Issue by mrbarletta** [Youshido/GraphQL#131]
doing a Mutation with a list of (AbstractInputObjectType) doesn't work sending the List in a variable.
But do work if the List is included in the mutation.

e.g. This works
```
mutation createMeeting(
            	$related_beans: RelatedBeanInputType
           )
           {createMeeting(
               name:"Meeting"
             , related_beans: [
                  {"module": "contacts", "id": "1"}
                 ,{"module": "contacts", "id": "2"}
                
             ]
               ){
                 id
               }
           }
```

This does not 
```
mutation createMeeting(
            	$related_beans: RelatedBeanInputType
           )
           {createMeeting(
               name:"Meeting"
             , related_beans: $related_beans
               ){
                 id
               }
           }
```
With variables:
```
{
    "related_beans": [
                    {"module": "contacts", "id": "5cc6be5b-fb86-2671-e2c0-55e749882d29"}
                   ,{"module": "contacts", "id": "2a135003-3765-af3f-bc54-55e7497e77aa"}

               ]
}
```

After hours of digging I found that fails due to the  `!$variable->isArray() `  in the file
https://github.com/Youshido/GraphQL/blob/master/src/Execution/Processor.php#L258

Which somehow doesn't validate when a variable is sent.

I tracked down the code to the point where isArray is suppose to be set to true  `            if ($this->match(Token::TYPE_LSQUARE_BRACE)) {` in this file
https://github.com/Youshido/GraphQL/blob/master/src/Parser/Parser.php#L142

But thats where I got lost - can't wrap my mind in the tokenizer and parser thing so I am here to ask you guys, is this a bug? or I am missing something?

**Comment by viniychuk** [comment]
@mrbarletta thanks, I know where to fix this, will do tonight

**Comment by crisu83** [comment]
@viniychuk did you fix this?

**Comment by viniychuk** [comment]
@mrbarletta Please, try to include a runnable example so it will be faster to fix next time, I made a false assumption when I read the issue and then it took some time to figure it out :)
@crisu83 fixed.

**Comment by mrbarletta** [comment]
sorry @viniychuk  I will next time!  

thanks for fixing this :+1:
