### ISSUE TITLE
Field definition of types only used in interfaces is not added to introspection query

### ISSUE THREAD

**Issue by fritz-gerneth** [Youshido/GraphQL#132]
When we have a custom type only used as part of an interface declaration, the type declaration is not added to the default introspection query. This then causes GraphiQL to fail as it encounters an unknown type on the interface declaration. 

Minimum schema to reproduce:

```
class MyCustomInterface extends AbstractInterfaceType
{
    public function build($config)
    {
        $config
            ->addField('myType', new MyNotDefinedType());
    }

    public function resolveType($object)
    {
        return new MyNotDefinedType();
    }
}

class MyNotDefinedType extends AbstractObjectType
{
    public function build($config)
    {
        $config->addField('id', new IdType());
    }
}

class MyRootType extends AbstractObjectType
{
    public function build($config)
    {
        $config->addField('interface', new MyCustomInterface());
    }
}

class MyInterfaceImplementation extends AbstractObjectType
{
    public function build($config)
    {
        $config
            ->applyInterface(new MyCustomInterface());
    }

    public function getInterfaces()
    {
        return [
            new MyCustomInterface(),
        ];
    }
}

$processor = new Processor(new Schema([
    'query' => new ObjectType([
        'name'   => 'RootQueryType',
        'fields' => [
            'myField' => [
                'type'    => new MyRootType(),
                'resolve' => function () {
                    return '';
                }
            ]
        ]
    ])
]));
```

However, this only occurs when there is no type implementing this interface added to the schema explicitly (like in the example above). When adding either type (`MyNotDefinedType ` or `MyInterfaceImplementation`) to the schema by other means (used somewhere else in the schema or adding it to the typelist manually) does the trick:

```
$schema->getTypesList()->addType(new MyNotDefinedTrick());
// oe
$schema->getTypesList()->addType(new MyInterfaceImplementation());
```

Also, this only affects the introspection query. Executing any other query works fine. I think this boils down to another issue: types only used as implementation of an interface are not available in the introspection query. Searching for the `MyInterfaceImplementation` type using the example above will not show any results. It is only then added to the schema when it is resolved to by the interface's `resolveType` method. Not sure if there is an easy way around beside manually adding it to the typelist (it then will show up).

**Comment by viniychuk** [comment]
@fritz-gerneth Yeah... that's because there's the `applyInterface` method which was not supposed to be there :) Anyway, thanks, it's an easy one

**Comment by fritz-gerneth** [comment]
So that's my code that is wrong for the `applyInterface` method in `MyInterfaceImplementation`? Thought that's only a shorthand for adding all fields of the interface to this type?

**Comment by viniychuk** [comment]
It did fix it in PR122 👍
