### ISSUE TITLE
Update the Graphiql version used in examples

### ISSUE THREAD

**Issue by StymiedSloth** [Youshido/GraphQL#140]
Can you please update the version in the examples. I was testing deprecated fields in a schema and they don't show up in the docs explorer. 

I checked the Graphiql source code and it has includeDeprecated flag for fields during introspection https://github.com/graphql/graphiql/blob/dc4a561f796258c6e6773612279abccb76f10ee0/src/utility/introspectionQueries.js#L37

Thanks

**Comment by viniychuk** [comment]
done. Also creating a separate repo for the demo. Will update readme soon.
