### ISSUE TITLE
Incorrect parsing of queries with duplicate fields

### ISSUE THREAD

**Issue by arthens** [Youshido/GraphQL#149]
I apologise for the cryptic title, I wasn't sure how to describe it better.

I ran into a problem with a query generated by relay, and _I think_ it might be a bug in how `Youshido/GraphQL` parses/handles the query. Could also be a gray area in graphql spec... not sure, I'm not too familiar with the specs.

Anyway, checkout [this example query](http://graphql.org/swapi-graphql/?query=query%20%7B%0A%20%20film(filmID%3A%201)%20%7B%0A%20%20%20%20title%0A%20%20%20%20%0A%20%20%20%20producers%0A%20%20%20%20%0A%20%20%20%20starshipConnection%20%7B%0A%20%20%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20%20%20hasPreviousPage%0A%20%20%20%20%20%20%20%20startCursor%0A%20%20%20%20%20%20%20%20endCursor%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20model%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20starshipConnection%20%7B%0A%20%20%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20%20%20hasNextPage%0A%20%20%20%20%20%20%20%20hasPreviousPage%0A%20%20%20%20%20%20%20%20startCursor%0A%20%20%20%20%20%20%20%20endCursor%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20length%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

As you can see `starshipConnection` is defined twice, and the 2 blocks request a slightly different set of fields. If you execute the query, the result will be a `starshipConnection` with the union of the required fields.

When I try to do something similar using `Youshido/GraphQL` I only get the fields requested by the second block. I suspect instead of doing a union of the 2 blocks, the second one just overrides the first one.

I don't have an public online endpoint I can link to, but this is what I see:
<img width="694" alt="mercatoetico_local_8091_graphql_explorer_query__7b_0a_09viewer__7b_0a____vendor_vid_3a_1___7b_0a______name_0a_______0a______gases__7b_0a________name_0a________id_0a_______7d_0a_______0a______gases__7b_0a________id_0a________gid_0a_______7d_" src="https://cloud.githubusercontent.com/assets/1178572/26631122/ec6be91c-4609-11e7-9081-36b079a50dc5.png">

Is this a bug in `Youshido/GraphQL`?

**Comment by arthens** [comment]
Just realised that one of my examples uses a connection and the other one a list, but it [it doesn't seem to matter](http://graphql.org/swapi-graphql/?query=query%20%7B%0A%20%20%0A%20%20person(personID%3A%202)%20%7B%0A%20%20%20%20name%0A%20%20%20%20%0A%20%20%20%20species%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20species%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20classification%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

**Comment by viniychuk** [comment]
@arthens you're correct, we haven't implemented this yet, will do in the future release

**Comment by portey** [comment]
@viniychuk, fixed in branch "origin/issue-fixes"

**Comment by viniychuk** [comment]
released in 1.5.1.
