### ISSUE TITLE
Is it possible to extend Types?

### ISSUE THREAD

**Issue by tommyJS** [Youshido/GraphQL#16]
Is there a possibility of extending types?
For example, if I have PostType and I want to create the next type called SpecialPostType (which has all fields that PostType has, but also a few additional), can I extend it somehow?

I do not want to use Interfaces, because as far as I understand, Interfaces will make me to define resolve functions for PostType and SpecialPostType separately.

**Comment by tommyJS** [comment]
Probably, it is not even present in the official GraphQL specification.

**Comment by viniychuk** [comment]
Hi @tommyJS , there's a way to do what you want and in fact, documentation is a bit outdated. Look at the latest change log. Now, you have Fields and you do not need to create multiple types. Also resolve function sits in Field (as it should be), not it Type. And to your question – I'm rolling new version with the `$config->addInterfaceMethods(new FieldInterface())` method which will do exactly what you want to do right now!

**Comment by viniychuk** [comment]
Using current (as of now – 1.1.5.3), you can create a base Type (if needed) with fields and re-use it in other classes. Also you can use `$config->applyInterface(new CharacterInterface())` method in your config.
