### ISSUE TITLE
Definition of args in object oriented approach.

### ISSUE THREAD

**Issue by tommyJS** [Youshido/GraphQL#17]
GraphQL Fields can have arguments. It is easy to do in inline-approach, however, I cannot achieve it in object oriented approach. I need it badly. I edited [this function](https://github.com/Youshido/GraphQL/blob/master/src/Config/Object/ObjectTypeConfig.php#L22) in the following way:
```
public function getRules()
    {
        return [
            'name'        => ['type' => TypeService::TYPE_STRING, 'required' => true],
            'description' => ['type' => TypeService::TYPE_STRING],
            'fields'      => ['type' => TypeService::TYPE_ARRAY_OF_FIELDS_CONFIG, 'final' => true],
            'interfaces'  => ['type' => TypeService::TYPE_ARRAY_OF_INTERFACES],
            'args'     => ['type' => TypeService::TYPE_ARRAY_OF_INPUT_FIELDS]
        ];
    }
```
However, still `$args` are empty in the `resolve` function. Do you know how to do that easily? I will be grateful for any help.

**Comment by viniychuk** [comment]
Do you have gitter? Login there, I'll help you, it's all simple, you're just not doing the way it's supposed to be :)

**Comment by viniychuk** [comment]
Anyway, here's an example of field with arguments:
```php
class LikePostField extends AbstractField
{
    public function resolve($value, array $args, ResolveInfo $info)
    {
        return $info->getReturnType()->getOne($args['id']);
    }

    public function getType()
    {
        return new PostType();
    }

    public function build(FieldConfig $config)
    {
        $config->addArgument('id', new NonNullType(new IntType()));
    }


}
```

**Comment by tommyJS** [comment]
Thank you very much. It works like a charm! Even, in my case:
```php
    public function resolve($value, array $args, ResolveInfo $info)
    {
        return $args['id'];
    }
```
is enough. Awesome! :100:
