### ISSUE TITLE
Enum values are incorrectly marked as deprecated

### ISSUE THREAD

**Issue by symm** [Youshido/GraphQL#171]
Steps to reproduce:

1. Create a schema containing an enum using `AbstractEnumType`
2. Do an introspection query using e.g. [get-graphql-schema](https://github.com/graphcool/get-graphql-schema)
3. The enum values are incorrectly reported as `@deprecated` because the deprecationReason defaults to an empty string instead of null 

![screen shot 2017-08-15 at 09 33 58](https://user-images.githubusercontent.com/69390/29308313-55835434-819d-11e7-9fe0-eac6ab7746ac.png)

**Comment by viniychuk** [comment]
@symm thanks for reporting, will take care of it.
