### ISSUE TITLE
Get parent values

### ISSUE THREAD

**Issue by armetiz** [Youshido/GraphQL#182]
Hi there.

Our schema
```graphql
roadMap {
  routeId,
  runs {
    id, 
    transportUnits {
      name
    }
  }
}
```

Transported units have to be sorted using a custom algorithm depending of a property that is owned on the road map.

```php
class RunType extends AbstractObjectType
{
    public function build($config)
    {
        $config
            ->addField('id', new StringType())
            ->addField(new Field([
                'name'    => 'transports',
                'type'    => new ListType(new TransportType()),
                'resolve' => function ($value, array $args, ResolveInfo $info) {
                    // to sort transports
                    // 1. find main route from road-map container
                    // 2. apply sort algorithm

                    return $value['transports'];
                },
            ]));
    }
}
```

The problem is.. That I don't know how to get this value ?
I'm seeing only 2 options:
1. Use the execution context to transfert the `routeId`.
2. Inject `routeId` from parent to bottom

The `RunType`is an internal class only accessible from `RoadMapType`; so option 2 does not seems to be so ugly.

But... i'm not convinced about those options... 
Do you have any idea ? Suggestion ?

Regards;

Thomas.

**Comment by fritz-gerneth** [comment]
May I suggest Option 3:  If sorting is mandatory and dependent on other values this really seems to be business logic for me. Hence, I'd suggest to handle business logic in a separate service, not in the presentation layer.

```
class RunType extends AbstractObjectType
{
    public function build($config)
    {
        $config
            ->addField('id', new StringType())
            ->addField(new Field([
                'name'    => 'transports',
                'type'    => new ListType(new TransportType()),
                'resolve' => function ($run, array $args, ResolveInfo $info) {
                        return $transportUnitService->findSorted($run->id);
                },
            ]));
    }
}
````
This decouples GraphQL from knowing that this data must be sorted in a specifical order.

**Comment by armetiz** [comment]
Yes, I agree with you.

I'll try this way.
Thanks ;)
