### ISSUE TITLE
IdType can't be null

### ISSUE THREAD

**Issue by seb2411** [Youshido/GraphQL#184]
In the case we want a nullable IdType currently GraphQL is converting `null` in empty string (""). I think it's a bug.

In IdType.php the current code:
```php
    public function serialize($value)
    {
        return (string)$value;
    }
```

The fix:
```php
    public function serialize($value)
    {
        if (null === $value) {
            return null;
        }
        return (string)$value;
    }
```

Can someone confirm me it's a bug or if there are a reason for this ?

Thank you.

**Comment by portey** [comment]
@seb2411, you're right, it's a bug. 
We'll try to fix it soon.

Thank you for your interest.

**Comment by seb2411** [comment]
Can I create a PR for this ?

**Comment by portey** [comment]
Of course, it would be nice.

**Comment by seb2411** [comment]
Done:
https://github.com/Youshido/GraphQL/pull/185

**Comment by portey** [comment]
@seb2411 , thank you very much.
We'll collect more changes and then add new tag.
