### ISSUE TITLE
How to use this without composer

### ISSUE THREAD

**Issue by jaffarcheckout** [Youshido/GraphQL#192]
I am having issue with my composer.  So, Can you please help me to install graphQL without composer.

**Comment by portey** [comment]
Hi, 

It's not supported from box, so you have to write your own autoload function + put source files somewhere in your project. How to write it you can look here http://php.net/manual/en/function.spl-autoload-register.php.

And I highly recommend you to fix your composer.

**Comment by portey** [comment]
@jaffarcheckout At this time i don't see any reason to keep this open. If you still feel the need for this please reopen this item.
