### ISSUE TITLE
No way to get requested fields of the object inside `resolve`

### ISSUE THREAD

**Issue by mrbarletta** [Youshido/GraphQL#2]
This issue is a request for having the Requested fields inside the resolve function.

The idea is not to retrieve unnecessary data. 

This has been tackled on graphql/graphql-js#19  - maybe you could get an idea.  

thanks

**Comment by viniychuk** [comment]
Hey, @mrbarletta! 
We've been working on this already. In fact, there's a huge update coming up by the end of this week with a lot of improvements along with 100% unit test code coverage, Relay support, and tons of bug fixes. You'll be able to get an access to those fields inside the resolve function.

We're also updating the whole structure/terms inside the library to be more compliant with the original JS GraphQL specs. If you want, you can hit me on gitter, I've just created a room for this repo.

**Comment by mrbarletta** [comment]
wow thats great!  I will take a look when is ready.  

We are using your library to build a sugarcrm graphql interface and learning along the way.

Thanks a lot

**Comment by mrbarletta** [comment]
Great! - this is already working on the latest version

each resolve has a new ResolveInfo $info   parameter that can be used like this:
```
$getFieldASTList=$info->getFieldASTList();
            $queryFields=[];
            foreach ($getFieldASTList as $key => $value) {
                $queryFields[$value->getName()]="";
            }
```

Here I got $queryFields array with each of the fields present in the query.
