### ISSUE TITLE
Extending AbstractField does not work for mutation fields

### ISSUE THREAD

**Issue by tommyJS** [Youshido/GraphQL#20]
Hi @viniychuk,

Maybe, I am doing something wrong, but when I try define mutations in such a way:
```php
private function getRootMutation() {
        return new ObjectType([
            'name' => 'RootMutation',
            'fields' => [
                // here's our likePost mutation
                'likePost' => new LikePost()
            ]
        ]);
    }
```
and then define LikePost in the following way:
```php
class LikePost extends AbstractField
{

    public function build(FieldConfig $config) {

        $config->addArgument('id', new NonNullType(new IntType()));
    }

    public function getType()
    {
        return new IntType();
    }

    public function resolve($value, array $args, ResolveInfo $info)
    {
        return 2;
    }
}
```

then it does not work. I receive error that `likePost` field is undefined.
I tried also extending `AbstractInputField`, however `InputFieldConfig` does not contain `addArgument` function.

Is it possible to do in the current version?

**Comment by viniychuk** [comment]
Can you show me the mutation request you're sending?

**Comment by viniychuk** [comment]
@tommyJS it looks like you're making a query instead of mutation

**Comment by tommyJS** [comment]
I do it in the following way:
```php
$processor = new Processor($productSchema);
$payload = 'mutation { likePost(id:1) }';
$processor->processPayload($payload);
$result = $processor->getResponseData();
```

**Comment by viniychuk** [comment]
@tommyJS , your example will work just fine in v1.1.4.5 although there's a couple of things to mention that could benefit you in the future.
1. By a convention try to name fields with the "Field" suffix. 
2. When adding a field as an object – you do not need a key (it's simply won't be used), because Field instance itself has a name which you can override by implementing `->getName` method.

Here's how it could look like:
```php
class LikePostField extends AbstractField
{

    public function build(FieldConfig $config) {

        $config->addArgument('id', new NonNullType(new IntType()));
    }

    public function getType()
    {
        return new IntType();
    }

    public function resolve($value, array $args, ResolveInfo $info)
    {
        return 2;
    }
}

$processor = new Processor(new Schema([
    'query' => new ObjectType([
        'name' => 'RootQueryType',
        'fields' => [
            'currentTime' => [
                'type' => new StringType(),
                'resolve' => function() {
                    return date('Y-m-d H:ia');
                }
            ]
        ]
    ]),
    'mutation' => new ObjectType([
        'name' => 'RootMutation',
        'fields' => [
            new LikePostField()
        ]
    ])
]));


$payload = 'mutation { likePost(id:1) }';
$processor->processPayload($payload);
echo json_encode($processor->getResponseData()) . "\n";
```

**Comment by tommyJS** [comment]
Thank you @viniychuk. "Field" suffix seems to obligatory.

**Comment by tommyJS** [comment]
@viniychuk I think that it might be good to do the following change in Readme.
```php
'likePost'   => new LikePostField(),
```
instead
```php
'likePost'   => new LikePost(),
```

**Comment by tommyJS** [comment]
Sorry, this convention is not obligatory in 1.1.4.5. (I had 1.1.4.3).

**Comment by tommyJS** [comment]
I think that I know what was the root cause of this issue.

It seems that in 1.1.4.3 version, the following convention was allowed for fields:
```php
'likePost' => new LikePost()
```

And additionally in 1.1.4.5 version also the following thing is allowed:
```php
'likePost' => new LikePostField()
```

But nothing different than that. It seems that I need to follow this convention and I think that it is worth adding to Readme. In fact, I can resolve this issue by implementing `getName` function, but it is not mentioned in Readme (also worth adding).

@viniychuk What about changing `getName` function to `getIdentifier` in AbstractField? It would be more intuitive, I think. Normally, Types have names in GraphQL.
