### ISSUE TITLE
connectionFromArraySlice incorrect slice

### ISSUE THREAD

**Issue by TheGhoul21** [Youshido/GraphQL#25]
ArrayConnection::connectionFromArraySlice is not slicing corretly when using "after" or "before" as parametersin the query

**Comment by viniychuk** [comment]
Thanks, will check soon.

**Comment by TheGhoul21** [comment]
I have a fix ready, just trying to understand how to create a pull request

**Comment by viniychuk** [comment]
merged and released in v1.1.4.9
