### ISSUE TITLE
NonNullType inside a List of InputObjects are able to be null

### ISSUE THREAD

**Issue by Zombaya** [Youshido/GraphQL#27]
As the title says, if you define a field inside an inputobject that is in a list to be NonNullable, the validator does not catch it if the variable is not set.

I've attached my test-classes: [TestMutation.zip](https://github.com/Youshido/GraphQL/files/407035/TestMutation.zip).

The query I tried to run:

    mutation{
      Test(test:{
        a:[
        ],
        b:[
          {
            c:"aaaa"
          },
          {
            
          }
        ],
      }) {
        name
      }
    }

The rules for TestInput:

    $config -> addField('a' , ['type' => new ListType(new IntType())        , 'description' => 'a'])
            -> addField('b' , ['type' => new ListType(new InputObjectType([
                                           'name'    => 'test_b',
                                           'fields'  => [
                                             'c'           =>  new NonNullType(new StringType()),
                                             ]
                                             ]))
                                          ])
            -> addField('d' , ['type' => new InputObjectType([
                                           'name'    => 'test_d',
                                           'fields'  => [
                                             'c'           =>  new NonNullType(new StringType()),
                                             ]
                                             ])
                                          ])

The validator does catch it if the field c of d is not set.

**Comment by viniychuk** [comment]
Thanks, will work on it

**Comment by viniychuk** [comment]
Hi @Zombaya , thanks again for reporting, I would ask you next time please,  try to create 1 file that could be executed just by running `php test.php` and include only non-working piece in it... It will be just easier for me to get right to the point.. 

Overall got fixed in v1.2.2.

**Comment by Zombaya** [comment]
I'll try, but I'm more used to execute graphql by using graphiql.  Next time I'll check how you do it in the tests-directory and make my testfile in the same fashion.
