### ISSUE TITLE
if i use TimestampType with value integer, it will return null after being resolved

### ISSUE THREAD

**Issue by hartono-sulaiman-kaskus** [Youshido/GraphQL#29]
$config->addField('date', new TimestampType());

In my database, i have field `date` as unix timestamp (which is integer)

In this class
https://github.com/Youshido/GraphQL/blob/master/src/Type/Scalar/TimestampType.php
```
public function isValidValue($value)
    {
        if (is_object($value)) {
            return true;
        }
        return is_int($value);
    }

```
if i pass an integer, it will return true
but when it is being serialized
```
 public function serialize($value)
    {
        if ($value === null || !is_object($value)) {
            return null;
        }
        return $value->getTimestamp();
    }
```
the previous valid integer will be serialized into null

**Comment by viniychuk** [comment]
@hartono-sulaiman-kaskus sorry, this class is invalid. In fact there shouldn't be such a Type, as this library was created as a part of our big project we missed to remove Timestamp as Date types that are not valid in general for GraphQL. You can now (as of v1.1.5.3) create your own ScalarTypes and implement them as you like. This one supposed to work with DB datetime type and thus shouldn't be called TimeStamp at all.. You can reach out to me in gitter if you need any help upgrading your schema.

**Comment by dilab** [comment]
@viniychuk what was the reason to remove Date type from the scalar type when keeping Datetime as one of the defined scalar types?
