### ISSUE TITLE
Minor documentation issue?

### ISSUE THREAD

**Issue by larswolff** [Youshido/GraphQL#4]
Hi,

First up - awesome work, I just started looking into this project after working with GraphQL-php for some time. I really like the OOP type declaration approach.

I come across an issue in the getting started document, which I think might just be outdated documentation?

    public function build(TypeConfigInterface $config)
    {
        $config
            ->addField('title', new NonNullType(new StringType()), [
                'description'       => 'This field contains a post title',
                'isDeprecated'      => true,
                'deprecationReason' => 'field title is now deprecated',
                'args'              => [
                    'truncated' => new BooleanType()
                ],
                'resolve'           => function ($value, $args) {
                    return (!empty($args['truncated'])) ? explode(' ', $value)[0] . '...' : $value;
                }
            ])
            ->addField('summary', new StringType())
            ->addField('likeCount', new IntType());
        $config->addArgument('id', new IntType());
    }

    public function resolve($value, $args, $info)
    {
        return [
            "title"     => "Title for the latest Post",
            "summary"   => "Post summary",
            "likeCount" => 2
        ];
    }

1) inline documentation says it is ObjectTypeConfig and not TypeConfigInterface.

2) addFields only takes 2 arguments, how is it configured then?

3) AbstractObjectType does'nt not contain a resolve() to override, and if I define a resolve function here, it is not called.

**Comment by viniychuk** [comment]
Hi, @larswolff, thanks for the comment, it is an outdated piece, I will check everything again to make sure it's all up to date. 
To answer your question I'll have to explain the latest changes we've done here.

1. We now have `types` and `fields` classes. GraphQL Type can't contain resolve function. It's just a type. So we made changes to conform this architecture piece.
2. As a result of 1st change – we now add fields with two options:
- `->addField('fieldName', array $fieldConfig)`
- `->addField(new FieldClass())`

You can find working example in our examples folder – https://github.com/Youshido/GraphQL/tree/master/examples, those are tested every time before publishing a new version. Also, there's a link to gitter chat where you can ask any questions and we'll try to support you asap.

**Comment by viniychuk** [comment]
This part of documentation was updated and there's a new version of documentation that's coming along with new features.
