### ISSUE TITLE
Middleware for ExecutionContext

### ISSUE THREAD

**Issue by viniychuk** [Youshido/GraphQL#47]
@svrcekmichal idea:
We need a way to pass some custom data in context? For example auth user, something like in https://github.com/graphql/express-graphql at the bottom of docs.

**Comment by viniychuk** [comment]
@svrcekmichal idea:
We need a way to pass some custom data in context? For example auth user, something like in https://github.com/graphql/express-graphql at the bottom of docs.

**Comment by viniychuk** [comment]
it's there. Documentation is on it's way, but in two words – there's a container that can be accessed from the `ResolveInfo`  via `->getContainer()` and from `->getExecutionContext()` on `Processor` class.

**Comment by dilab** [comment]
@viniychuk  You mentioned how to get the values. But how do we set the values at first place.

**Comment by dilab** [comment]
This is how we do it, in case someone else stumbles on this thread:

```
 $container = new Container();

        $container->set('user', $user);

        $executionContext = new ExecutionContext($this->schema);

        $executionContext->setContainer($container);

        $processor = new Processor($executionContext->getSchema());

        $processor->getExecutionContext()->setContainer($container);

        return $processor->processPayload($query, $variables, $reducers)->getResponseData();

```

**Comment by fritz-gerneth** [comment]
I think you shouldn't overwrite the Container - this will remove values set by other parts of the applications (or the lib itself). The execution context has a container instance by default which can easily be accessed:
```
        $processor = new Processor($this-schema);
        $processor->getExecutionContext()->getContainer()->set(
            'user,
            $user
        );  
```

Looking forward to see when we'll be able to create field objects by a service manager / factory. This should get rid of most times you need to get the container :)
