### ISSUE TITLE
How to create a Mutation with a  List of (something) as argument

### ISSUE THREAD

**Issue by mrbarletta** [Youshido/GraphQL#6]
Lets say I have a mutation like this
```
mutation
{createPost(
  title: 'Copa America', 
  description: ' Latest results ',
  authors: [  
     {name: 'Maradona', email: 'maradona@gmail.com' } ,
     {name: 'Messi', email: 'messi@gmail.com' } ]  
)}
```
How Do I handle this scenario? - 

I tried the author ListType( new AuthorType()) ? 

ListType is not iterating each AuthorType  sent on the request so its failing with `Not valid Type....` 

ResolveValidator line
```
if (!$argumentType->isValidValue($argumentType->parseValue($argument->getValue()->getValue()))) {
```
Is receiving the entire array sent  and not a single iteration..

I guess we need a InputListType ? or I am missing something

**Comment by viniychuk** [comment]
Ok, so the thing here is that your AuthorType should also be an InputType e.g. extended from AbstractInputObjectType. Details in Gitter :)

**Comment by viniychuk** [comment]
And example for future references.
```
$config->getMutation()->addFields([
            'createProperty' => [
                'type' => new PropertyType(),
                'args' => [
                    'title' => new StringType(),
                    'tenants' => new ListType(new InputTenantType()),
                ],
                'resolve' => function($value, $args, $info) {
                    // do your insert
                    return [];
                }
            ]
        ]);
```
