### ISSUE TITLE
Bug: invalid output type returned without error if NonNull type used

### ISSUE THREAD

**Issue by svrcekmichal** [Youshido/GraphQL#60]
If `!Int` is resolved to `null`, there's no error or exception thrown

```
$config->addField('id', [
  'type' => new NonNullType(new IntType()),
  'resolve' => function() { return null; }
]);
```

`graphql-js` is notificating about this behavior with 

```
{
      "message": "Cannot return null for non-nullable field User.id.",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ]
    }
```

in response `errors` key. Same is returned if resolver returns string not coercible to int.

**Comment by viniychuk** [comment]
fixed in https://github.com/Youshido/GraphQL/releases/tag/v1.4
