### ISSUE TITLE
Fragment reference "fReservation" not found on model "CourtReservation"

### ISSUE THREAD

**Issue by rudiedirkx** [Youshido/GraphQL#63]
Full query:

```
query {
    user {
        ...fUser
        reservations {
            ...fReservation
        }
    }
}
fragment fReservation on Reservation {
    id
    ... on CourtReservation {
        players {
            id
            user {
                ...fUser
            }
        }
    }
    ... on ClassReservation {
        user {
            ...fUser
        }
    }
}
fragment fUser on User {
    id
    fullname
}
```

When I debug `ResolveValidator::assertValidFragmentForField()`, `$fragment->getModel()` seems to be `"User"`.

Where does User come from..? The fragment is only applied to `reservations`, which is a `new ListType(new ReservationInterface())`. Is it confused by `fUser`?

When I try [another server library](https://github.com/webonyx/graphql-php), the query works. Which is wrong? The query seems correct...

**Comment by rudiedirkx** [comment]
I'm using the OOP approach btw:

```
class ReservationInterface extends AbstractInterfaceType {
class CourtReservationType extends AbstractObjectType { // implements ReservationInterface
class ReservationPlayerType extends AbstractObjectType {
class ClassReservationType extends AbstractObjectType { // implements ReservationInterface
class UserType extends AbstractObjectType {
```

If I move all fields from fragments inline (no more fragments), the query works.

**Comment by viniychuk** [comment]
@rudiedirkx working on it, will push an update asap

**Comment by AndreasHeiberg** [comment]
Was about to post about the fact that Fragments on an interface does not work for the actual implementations of that interface. Seems duplicate to this. Will be keen to follow.

**Comment by AndreasHeiberg** [comment]
Any updates on this?

**Comment by Schunk** [comment]
I got the same problem, and adding this to my type seems to work:

```php
    public function isCompositeType()
    {
        return true;
    }

    public function getTypeOf()
    {
        return new PersonInterface(); // Your interface here
    }
```

**Comment by AndreasHeiberg** [comment]
@Schunk that does not fix the underlaying issue. It allows you to make a fragment on the interface but not specifically on any of the concrete types.

Fixing this would be a massive step towards making this library production ready.

**Comment by viniychuk** [comment]
fixed in https://github.com/Youshido/GraphQL/releases/tag/v1.4
