### ISSUE TITLE
Confusing of the naming

### ISSUE THREAD

**Issue by dilab** [Youshido/GraphQL#66]
I think the name [Field](https://github.com/Youshido/GraphQL) used for GraphQL(Youshido) is different from [Field](https://facebook.github.io/graphql/#sec-Type-System) in GraphQL documentation.

Field in GraphQL(Youshido) refers to an instance of a type(object) (including the resolve method). 
Field in GraphQL(doc) refers to property of a object. 

If my understanding is correct. Shall we use another name for Field for Youshido?

**Comment by viniychuk** [comment]
@dilab I'm sorry you got confused, but your statement is not accurate. Both "fields" refers to an instance of an object property which is implemented as a re-usable instance in PHP. 
We have a notion of `Type` as well and you can extend a type by extending from `AbstractType`, `AbstractObjectType` and so on. On the other hand you can create a `Field` either as a class or as a property of another object. Hit me on Gitter if you have more questions
