### ISSUE TITLE
Mutation helper class - how to

### ISSUE THREAD

**Issue by Vendium** [Youshido/GraphQL#68]
Hi,

I have a Yii project that i have implemented with Youshido/GraphQL and it works great! 

Based on Yiis classes i can autogenerate code for querys and now im looking on mutation. 

Smal repo: https://github.com/Vendium/Youshido-GraphQL-Yii

In your documentation you have written that "You can create a mutation by extending AbstractObjectType", my question is how to do this so you dont get a big Schema file. For query its made easy by working with types that have relations with each other. 

So dose any one have a small code exampel of how to work with mutations without geting a big schema file and what i assume is to place mutations in type files. 

thanks!

**Comment by viniychuk** [comment]
Hi @Vendium,

You can create a separate `MutationType` class and then store all mutation fields there, next step would be to start creating a separate classes and then in main Mutation class `build` function you can call `$config->addFields(UserMutations->getFields())` but that would be necessary if you have more then, let's say, 100 mutations which is a lot.

A natural way to do so probably would be to have different endpoints with different schemas (again, if you have a lot of mutations/queries). You can hit me in gitter (link in readme) if you want to discuss it.
