### ISSUE TITLE
Non-null field can return null in response

### ISSUE THREAD

**Issue by svrcekmichal** [Youshido/GraphQL#72]
tried on last version

schema:
```
type Query {
  user: User
} 
type User {
  key: Int!
}
```

query:
```
{
  user {
    key 
  }
}
```

If i user `graphql-js`:
```
{
  "data": {
    "user": null
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable field User.key.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}
```

With this package:
```
{
  "data": {
    "user": {
      "key": null
    }
  }
}
```
There is no error thrown

**Comment by Naoto-Ida** [comment]
I'm really interested in contributing to this lib. I'm going to check it out :)
(Ex. mainly PHP guy who jumped on the JS implementation and am now interested in a PHP implementation...)

**Comment by portey** [comment]
@Naoto-Ida , hi

This lib works, and we use it on production, but(!) there're several bugs in resolving non-nullables and with variables usage. To fix bugs we need to refactor processor a lot and now we're fixing it in branch "processor-refacotor", so I hope very soon we'll make new release with all issues fixed.

**Comment by viniychuk** [comment]
fixed in https://github.com/Youshido/GraphQL/releases/tag/v1.4
