### ISSUE TITLE
Optional argument throws if missing in query

### ISSUE THREAD

**Issue by svrcekmichal** [Youshido/GraphQL#73]
schema: 
```
type Query {
  getSomething(sort:SortType): String //sort not required
}
```

query: 
```
query SomeQuery($sort:SortType) {
  getSomething(sort: $sort)
}
```

variables: 
NONE or 
```
{}
```

response
```
{
  "errors": [
    {
      "message": "Variable \"sort\" does not exist for query \"getSomething\""
    }
  ]
}
```

**Comment by portey** [comment]
@svrcekmichal, thank you for your reporting! 
This bug is already fixed but not published and will be published very soon. So I leave this issue opened to new release.

**Comment by viniychuk** [comment]
fixed in https://github.com/Youshido/GraphQL/releases/tag/v1.4

**Comment by rovansteen** [comment]
Are you sure this is fixed? I'm still having this issue. Running version 1.2 of `youshido/graphql-bundle`. The problem only occurs when using a variable, if I pass null directly as value it does work correctly.

**Comment by svrcekmichal** [comment]
@rovansteen Yes and no, in changelog
```
Optional arguments now work correctly (but don't forget to list them with a null value, otherwise you will get an error according to the graphql spec)
```
but I didn't found that in spec. but according to @viniychuk you have to define variables with null, so to fix my example above, you should use variables `{"sort":null}`

I have tested this today in graphql-js and you don't need to do that in that package

**Comment by rovansteen** [comment]
Ah, that explains. I'm using Apollo Client on the client side and it does not set variables to null if you don't include them unfortunately. Thanks for you answer!
