### ISSUE TITLE
NonNullType not casting to string in query

### ISSUE THREAD

**Issue by webmozart** [Youshido/GraphQL#80]
I'm using `NonNullType` in my return type like this:

~~~php
class PersonType extends AbstractObjectType
{
    /**
     * @param ObjectTypeConfig $config
     *
     * @return mixed
     */
    public function build($config)
    {
        $config->addFields([
            'id' => new NonNullType(new IdType()),
            'firstName' => new NonNullType(new StringType()),
            'lastName' => new NonNullType(new StringType()),
        ]);
    }
}
~~~

The IDs of my persons are UUIDs. With the code like this, the result is:

~~~json
{
    "data": {
        "persons": [
            {
                "id": {},
                "firstName": "Bernhard",
                "lastName": "Schussek"
            }
        ]
    }
}
~~~

As you can see, the UUID is not cast to a string, but converted to `{}`. However if I remove the `NonNullType` around `IdType`, the result is as expected:

~~~json
{
    "data": {
        "persons": [
            {
                "id": "6cfb044c-9c0a-4ddd-9ef8-a0b940818db3",
                "firstName": "Bernhard",
                "lastName": "Schussek"
            }
        ]
    }
}
~~~

**Comment by viniychuk** [comment]
@webmozart is your UUID an object that has `__toString` method or is it a plain string? Trying to reproduce your case and even though it works with the latest version, I cannot achieve the same results with the old one...

**Comment by viniychuk** [comment]
@webmozart got it, it didn't work with objects, will work in tonights release – v1.3.1

**Comment by viniychuk** [comment]
fixed in https://github.com/Youshido/GraphQL/releases/tag/v1.4
