### ISSUE TITLE
Fragments do not appear to work

### ISSUE THREAD

**Issue by alexbowers** [Youshido/GraphQL#83]
```
{
            oneComparison: Post(id: 1) {
                title
            }
            twoComparison: Post(id: 1) {
                ...Fields
            }
        }
        
        fragment Fields on Post {
            title
        }
```

Returns this:

```json
{"data":{"oneComparison":{"title":"string"},"twoComparison":[]}}
```

**Comment by viniychuk** [comment]
@alexbowers I added test in the commit attached above (https://github.com/Youshido/GraphQL/commit/5cdde02b3da85c374112b396383a5018221e3888) and it looks like everything's working. Please, attach the full test that doesn't work for you so I can assist.
