### ISSUE TITLE
Strange issue with list of values

### ISSUE THREAD

**Issue by svrcekmichal** [Youshido/GraphQL#86]
Hi
Query:
```
mutation {
  upvote(idPhotos:[320131273]) {
    id
  }
}
```

If i define `idPhotos` this way
```
$config->addArgument('idPhotos', new NonNullType(new ListType(new IntType())));
```
I get error `Not valid type for argument "idPhotos" in query "upvote"`, but if I define it this way
```
$config->addArgument('idPhotos', new NonNullType(new ListType(new NonNullType(new IntType()))));
```
everything works as expected.

**Comment by viniychuk** [comment]
@svrcekmichal got it... checking.

**Comment by portey** [comment]
Hi

I checked this issue and everything works fine for me. 
@svrcekmichal, problem still exists? Do you use last version? 

I wrote test for it [here](https://github.com/Youshido/GraphQL/blob/develop/Tests/Schema/NonNullableTest.php#L137), can you check is it the same as yours?

**Comment by viniychuk** [comment]
@svrcekmichal reopen this if it's still the case, I double checked and it seems to be working for me too..
