### ISSUE TITLE
DateTimeType clarification

### ISSUE THREAD

**Issue by stefanorg** [Youshido/GraphQL#89]
Hi,
using DateTimeType enforce string validation against a date format, i found that the actual implementation of DateTimeType doesn't allow `null` value as mutation parameter and as scalar value.

As an example if in the `todo` example app we add a `expire` field as DateTime we can query

```
class TodoType extends AbstractObjectType
{
    public function build($config)
    {
        $config->addFields([
            'id' => new NonNullType(new IdType()),
            'title' => new StringType(),
            'completed' => new BooleanType(),
            'expire' => new DateTimeType("d-m-Y")
        ]);
    }

}
```
if we issue a query

```
fragment todo on Todo {
  id
  title
  completed
  expire
}

{
  todos {
    ...todo
  }
}
```

we get

```
{
  "data": {
    "todos": [
      null
    ]
  },
  "errors": [
    {
      "message": "Not valid resolved type for field \"expire\""
    }
  ]
}
```

Also in case of mutation

```
mutation {
   save(id:1, title: "todo mod", expire: null) {
    ...todo
  }
}
```

the error is

```
{
  "data": {
    "save": null,
    "toggleAll": [
      null
    ]
  },
  "errors": [
    {
      "message": "Not valid type for argument \"expire\" in query \"save\"",
      "locations": [
        {
          "line": 10,
          "column": 34
        }
      ]
    },
    {
      "message": "Not valid resolved type for field \"expire\""
    }
  ]
}
```

**Comment by stefanorg** [comment]
Another point that is not clear to me about types, in this case about DateTimeType is how we should expect this value in the resolve function?
I mean if i have a `expire` date field, in my resolve function should i expect a formatted string or a DateTime object?

```
public function resolve($value, array $args, ResolveInfo $info)
    {
       $expire = $args['expire']; 

        // it's up to me to do the conversion ?
        // why expire is not already a DateTime ?

        return $dispositivo;
    }
```

**Comment by viniychuk** [comment]
@stefanorg DateTime is going to be separated into a GraphQLAddons-ish bundle. Also it's going to be updated to work correctly (hotfix was applied to the current version, but it will be re-written).

**Comment by maarekj** [comment]
The DateTimeType and DateTimeTzType do not seem not to accept null value.

**Comment by viniychuk** [comment]
@maarekj it now works properly. Releasing new version.
