### ISSUE TITLE
Null value is a valid value with the October 2016 GraphQL release

### ISSUE THREAD

**Issue by stefanorg** [Youshido/GraphQL#90]
Based on this release: https://github.com/facebook/graphql/releases/tag/October2016

The library should support `null` value. 
As an example see issue #89 where DateTimeType throw error both for "unserialize" and "serialize" null value as parameter.

If you can give feedback i can provide a PR for this maybe.

**Comment by viniychuk** [comment]
fixed in dev, will be published in the next release.
