### ISSUE TITLE
Resolve function - Pass a bag of arguments instead of an array

### ISSUE THREAD

**Issue by jamhall** [Youshido/GraphQL#92]
Hello,

Thanks for your great work!

It would be really nice if the arguments passed to the resolve function were stored in a bag rather than a standard array.  For example:

We create an `ArgumentBag` class:

```php
class ArgumentBag implements \IteratorAggregate, \Countable
{
  private $arguments;

  public function add(array $arguments = array())
  {
      $this->arguments = array_replace($this->arguments, $arguments);
  }

  public function get($key, $default = null)
  {
      return array_key_exists($key, $this->arguments) ? $this->arguments[$key] : $default;
  }

  public function has($key)
  {
      return array_key_exists($key, $this->$arguments);
  }

  public function set($key, $value)
  {
      $this->arguments[$key] = $value;
  }

  public function getIterator()
  {
      return new \ArrayIterator($this->arguments);
  }

  public function count()
  {
      return count($this->arguments);
  }
  
}
```

And we can pass this to the resolve function and have a more object-oriented way of dealing with parameters:

```php
    public function resolve($value, ArgumentBag $args, ResolveInfo $info) {
        // get argument value if exists, otherwise return default of 10
       // nicer than doing isset($args['limit']) ? $args['limit'] : 10;
        $limit = $args->get('limit', 10);
        if($args->has('name')) {
            // do something with name...
        }
   }
```

Let me know your thoughts...

Thanks!

**Comment by jamhall** [comment]
I have implemented this into my fork: 

https://github.com/jamhall/GraphQL/commit/ff733be1dc9c00fc4bdd30e1e3d078c89d380191

All tests are passing.

**Comment by brayniverse** [comment]
Could you use [`ArrayAccess`](http://php.net/manual/en/class.arrayaccess.php) for backwards compatibility?

**Comment by fritz-gerneth** [comment]
Imho this would break a lot of code already relying on `$args` being an array (not of this lib itself, but of everyone using it :)) 
I generally like the idea of passing an bject form for this, yet I think such simple data contains should stick to the objects already available from the SPL.

To my knowledge even using an `ArrayObject` / `ArrayAccess` implementation wouldn't work as this is not compatible with arrays either. Functions like `array_key_exists`, `array_push` do not work with `ArrayAccess` as far as I remember (as do the comments on the documentation http://php.net/manual/en/class.arrayaccess.php )?

**Comment by jamhall** [comment]
@brayniverse  - Hi! Good idea! I'll have a look

**Comment by brayniverse** [comment]
Submitted a PR to your fork.

**Comment by roippi** [comment]
I'm a -1 on this, this is "OO for the sake of OO."

Also, there is no way this can be made backwards-compatible, even with `ArrayAccess`.  Consider:

```
'resolve' => function($value, $args, $info) {
  return empty($args) ? 'foo' : 'bar';
}
```

There is no way to make `ArgumentBag` pass this test.

**Comment by jamhall** [comment]
I've made the following changes: https://github.com/jamhall/GraphQL/commit/6ba82917c7aa986bd1d21a651944ef4418ee7b98

It is now backwards compatible. The only problem is the `args` argument for the resolve function in the `FieldInterface` cannot be type enforced.

```
    public function resolve($value, $args, ResolveInfo $info);
```

Both examples from my project work:

```php

public function resolve($value, $args, ResolveInfo $info) {
    $limit = $args->get('limit', 10);
    $partService = $this->container->get('dao.part');
    return $partService->getAllParts($limit);
}
```

And 
```php
public function resolve($value, $args, ResolveInfo $info) {
    $limit = isset($args['limit']) ? $args['limit'] : 10;
    $partService = $this->container->get('dao.part');
    return $partService->getAllParts($limit);
}
``

**Comment by jamhall** [comment]
@roippi  - You're right. That would indeed fail. 

"OO for the sake of OO." I don't agree. Everything else is object-oriented in this project, it would be nice if this was too! IMHO, it keeps the code cleaner.

**Comment by roippi** [comment]
This will also fatal in PHP7 for anyone who has typehinted their resolvers as such:

`function($value, array $args, $info)`

**Comment by jamhall** [comment]
It is not 100% fully backwards-compatible - Agreed. If accepted, I don't expect it to get merged immediately, but it would be nice if it is considered for the next major release.

**Comment by fritz-gerneth** [comment]
For me this would be just another custom DTO / data container not compatible with all the other "object"ified arrays from all the other libraries out there. 
It's not that I don't see the benfit of using some object on this here. It's rather more that this object most likely is not compatible with the libraries I use in my business layer. So I'd have to have yet another wrapper/mapper to make it compatible with my code / other libraries. For me, the common interface for this is exactly an array. It doesn't make any assumptions on my code - it's just there, no need to map one object into another etc.. 

I see the GraphQL expl. not making any assumptions about the implementation. So does this library. Whiile it might seem sufficient to have such rather small container for data, it most likely will never fit all use-cases. Eventually most people will convert this container into the data structure they need (just as you are doing now). If you rather more like to operate on an object, it is really only one line you can add to your resolver to cast it in the exact data structure you want / need. So array is the least common ground on how to provide the data to the resolver.

**Comment by viniychuk** [comment]
You guys made it really hard to make the right decision on this one, I completely changed my mind after reading the whole thread :) 
On the one hand I'd agree with @fritz-gerneth Even thought it's a nice thing to have and I was thinking about doing it myself it's not possible to bring something really cool like `$args->getTitle()` for our users. The only thing here is `$args->has('title')` instead of `array_key_exists`. I'd say it's better to use default values in GraphQL Schema instead of making them on the Bag level. Plus to make it work with objects we'll need to introduce some logic like `$args->get('user/gender', 'm')` or `$args->get('user.gender', 'm')` and I'm not sure this would be a good approach. 
On the other hand – I'd like to have a cleaner code in resolvers.  Will get back here later with some arguments.

**Comment by portey** [comment]
Hi,

+1 to use `ArgumentBag` instead of array. 

But there're else one thing which is very uncomfortable - work this nullable arguments. For example, if we have nullable boolean argument and standard array approach, we should write this: 
```php 
if (isset($args['active']) && is_bool($args['active']) ) { 
```

For OOP approach it would be nice to have something like this: 
```php 
if($args->hasBoolean('active')) {
```

The decision on this one must be very flexible and must cover working with nullable arguments.

**Comment by roippi** [comment]
If this is implemented, please at least figure out a way to make it opt-in, via config or some runtime setting.  I just audited our codebase and this would be quite disruptive, many resolvers would need to be rewritten.

**Comment by jamhall** [comment]
@roippi  I think adding an adapter would be a very reasonable solution. Something along the lines of:

```
$processor->setArgumentAdapter(ArgumentArrayAccessorAdapter::class)
```

or 

```
$processor->setArgumentAdapter(ArgumentObjectAccessorAdapter::class)
```

Or something like that...

**Comment by jamhall** [comment]
And for bc issues, we could default to standard array access

**Comment by colinmollenhour** [comment]
As a user that is considering starting a new GraphQL implementation (versus maintaining an existing one) the ArgumentBag looks like a good idea to me since I hate writing stuff like `isset($a['b']) ? $a : NULL` all the time and it is even worse when I have to clean up other people's code because of PHP warnings because they were lazy and used a raw `$a['b']`. Just my $0.02 as a newcomer.
