### ISSUE TITLE
Exception in parseValue functions

### ISSUE THREAD

**Issue by portey** [Youshido/GraphQL#93]
It's not good decision to throw exception in `parseValue` method of type. It is about parseValue in `AbstractInputObjectType`.  Method `isValidValue` is responsible for validation of input value.

Also using PHP standard exception is out of date, the better choice is to use exception which implement `LocationableInterface`.

**Comment by viniychuk** [comment]
Thank you @portey, but you're mixing two things here. In fact,`parseValue` is exactly the place to through an exception if we cannot parse the value, it's just so happen it was used in `isValidValue`which is a different story, so let's talk it through first.
