### ISSUE TITLE
Parsing error on a list of nonNull ids [ID!]

### ISSUE THREAD

**Issue by brunoreis** [Youshido/GraphQL#95]
I have this schema for the args on the server: 

```php
    'message_ids' => new ListType(
        new NonNullType(
            new IdType()
        )
    )
```

When I inspect it using the GraphiQL client, it shows me this: 

```js
registerThread(message_ids: [ID!]): Thread
````

I have this mutation defined on the client (Apollo): 

```js
mutation registerThread($message_ids: [ID!] ) {
    registerThread(message_ids: $message_ids) {
...
}}
```

When I send data to the server, the server returns this error: 

```js
{
  "errors": [
    {
      "message": "Unexpected token \"RSQUARE_BRACE\"",
      "locations": [
        {
          "line": 1,
          "column": 43
        }
      ]
    }
  ]
}
```

I found a workaround because I can live without the nonNull requirement. [ID] is just fine for me. But, I decided to report just in case this is really a parser error.

**Comment by viniychuk** [comment]
@portey can you look at this one, please? :)

**Comment by viniychuk** [comment]
@brunoreis Thank you for reporting the issue, will be addressed.

**Comment by portey** [comment]
@viniychuk, fixed in dev branch

**Comment by viniychuk** [comment]
@portey Thank you!
