### ISSUE TITLE
more debugging possibilities

### ISSUE THREAD

**Issue by lhyx** [Youshido/GraphQL#96]
Dear sir,

For example when executing a mutation when a type is not valid could there be an error that says which fields in the type are not valid ? When working with big types this is really helpful.

 "message": "Not valid type for argument \"Object\" in query \"createObject\"",

If object is a really big type you have to check every field in the object to find the problem.

Maybe add the possibility to specify a logger according to the PSR-3 standard ?

Thanks in advance.

**Comment by viniychuk** [comment]
Hi @lhyx , I'm releasing a version with much more detailed error information that actually tells you exact field and exact problem

**Comment by viniychuk** [comment]
@lhyx try v1.4.2.17. Also logger will be available in the 1.5 which is coming next week (I hope :))
