### ISSUE TITLE
Problem with passing InputObjectType as argument with relation to ListType

### ISSUE THREAD

**Issue by m-naw** [Youshido/GraphQL#99]
Hi,

I started to use Symfony bundle created by you. Thanks for committing into it.

After some time I got to the problem which may be a bug.

I prepared classes like that :

```php
class ItemType extends AbstractObjectType
{
    public function build($config)
    {
        $config->addFields([
            'id'        => new NonNullType(new IdType()),
            'custom' => new CustomField(),
        ]);
    }
}
```

```php
class CustomField extends AbstractContainerAwareField
{
    public function build(FieldConfig $config)
    {
        $config->addArguments([
            'argX' => new NonNullType(new ArgXInputType())
        ]);
    }

    public function resolve($value, array $args, ResolveInfo $info)
    {
        return ['string' => 'some string'];
    }

    public function getType()
    {
        return new CustomType();
    }
}
```

```php
class CustomType extends AbstractObjectType
{
    public function build($config)
    {
        $config->addFields([
            'string' => new StringType(),
        ]);
    }
}
```

```php
class ArgXInputType extends AbstractInputObjectType
{
    public function build($config)
    {
        $config->addFields([
            'x' => new NonNullType(new BooleanType()),
        ]);
    }
}
```

now I have 2 fields one with single object type:

```php
class ItemField extends AbstractContainerAwareField
{
    public function build(FieldConfig $config)
    {
        $config->addArguments([
            'id' => new NonNullType(new IdType())
        ]);
    }

    public function resolve($value, array $args, ResolveInfo $info)
    {
        return $this->container->get('some_repo')->find($args['id']);
    }

    public function getType()
    {
        return new ItemType();
    }
}
```

and list 

```php
class ItemsField extends AbstractContainerAwareField
{
    public function build(FieldConfig $config)
    {
        $config->addArguments([
            'example' => new StringType(),
        ]);
    }

    public function resolve($value, array $args, ResolveInfo $info)
    {
        return $this->container->get('some_repo')->findBy($args);
    }

    public function getType()
    {
        return new ListType(new ItemType());
    }
}
```

Now when I execute :

```
{
  item(id:2) {
    id
    custom(argX: {x: true}) {
      string
    }
  }
}
```

I've got valid response : 

```
{
  "data": {
    "item": {
      "id": "2",
      "custom": {
        "string": "some string"
      }
    }
  }
}
```

but when I want to fetch list

```
{
  items {
    id
    custom(argX: {x: true}) {
      string
    }
  }
}
```

 I've got something like that : 

```
{
  "data": {
    "items": [
      {
        "id": "1",
        "custom": {
          "string": "some string"
        }
      },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ]
  },
  "errors": [
    {
      "message": "Not valid type for argument \"argX\" in query \"custom\"",
      "locations": [
        {
          "line": 8,
          "column": 16
        }
      ]
    },
    {
      "message": "Not valid type for argument \"argX\" in query \"custom\"",
      "locations": [
        {
          "line": 8,
          "column": 16
        }
      ]
    },
    {
      "message": "Not valid type for argument \"argX\" in query \"custom\"",
      "locations": [
        {
          "line": 8,
          "column": 16
        }
      ]
    },
    {
      "message": "Not valid type for argument \"argX\" in query \"custom\"",
      "locations": [
        {
          "line": 8,
          "column": 16
        }
      ]
    },
    {
      "message": "Not valid type for argument \"argX\" in query \"custom\"",
      "locations": [
        {
          "line": 8,
          "column": 16
        }
      ]
    },
    {
      "message": "Not valid type for argument \"argX\" in query \"custom\"",
      "locations": [
        {
          "line": 8,
          "column": 16
        }
      ]
    },
    {
      "message": "Not valid type for argument \"argX\" in query \"custom\"",
      "locations": [
        {
          "line": 8,
          "column": 16
        }
      ]
    },
    {
      "message": "Not valid type for argument \"argX\" in query \"custom\"",
      "locations": [
        {
          "line": 8,
          "column": 16
        }
      ]
    },
    {
      "message": "Not valid type for argument \"argX\" in query \"custom\"",
      "locations": [
        {
          "line": 8,
          "column": 16
        }
      ]
    }
  ]
}
```

So as u see for the first row argument is valid, for the rest arguments are empty.

I didnt try to solve it by mutation as my operation doesnt modify data, it just calculates price base on object passed as argument. It seems to be valid graphql query ? When I operate on ex. StringType as argument instead of ObjectInputType (ArgXInputType in this example) it works fine with List.

I will try to dig into the code but its my first day with this lib so it may take a while.

**Comment by viniychuk** [comment]
@m-naw thanks for reporting... It looks like we have a problem there yet we use similar schema all the time. Will take a closer look in a day or two

**Comment by m-naw** [comment]
Hi @viniychuk 

I wanted to check if you had opportunity to look into that problem?

**Comment by viniychuk** [comment]
@m-naw yes, wasn't able to release a new version due to a lot of updates, will issue this particular patch separately

**Comment by m-naw** [comment]
@viniychuk and @jasonbahl tell me if Im wrong but issue seems to exist in Youshido\GraphQL\Execution\Processor::prepareAstArguments method.

As in first list iteration arguments dump looks like this before function is being called:

``
array(2) {
  [0]=>
  object(Youshido\GraphQL\Parser\Ast\Argument)#898 (3) {
    ["name":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    string(8) "location"
    ["value":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    object(Youshido\GraphQL\Parser\Ast\ArgumentValue\InputObject)#899 (2) {
      ["object":protected]=>
      array(2) {
        ["lat"]=>
        string(4) "51.5"
        ["lon"]=>
        string(1) "0"
      }
      ["location":"Youshido\GraphQL\Parser\Ast\AbstractAst":private]=>
      object(Youshido\GraphQL\Parser\Location)#900 (2) {
        ["line":"Youshido\GraphQL\Parser\Location":private]=>
        int(42)
        ["column":"Youshido\GraphQL\Parser\Location":private]=>
        int(24)
      }
    }
    ["location":"Youshido\GraphQL\Parser\Ast\AbstractAst":private]=>
    object(Youshido\GraphQL\Parser\Location)#901 (2) {
      ["line":"Youshido\GraphQL\Parser\Location":private]=>
      int(42)
      ["column":"Youshido\GraphQL\Parser\Location":private]=>
      int(14)
    }
  }
  [1]=>
  object(Youshido\GraphQL\Parser\Ast\Argument)#902 (3) {
    ["name":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    string(4) "unit"
    ["value":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    object(Youshido\GraphQL\Parser\Ast\ArgumentValue\Literal)#903 (2) {
      ["value":"Youshido\GraphQL\Parser\Ast\ArgumentValue\Literal":private]=>
      string(2) "mi"
      ["location":"Youshido\GraphQL\Parser\Ast\AbstractAst":private]=>
      object(Youshido\GraphQL\Parser\Location)#904 (2) {
        ["line":"Youshido\GraphQL\Parser\Location":private]=>
        int(42)
        ["column":"Youshido\GraphQL\Parser\Location":private]=>
        int(56)
      }
    }
    ["location":"Youshido\GraphQL\Parser\Ast\AbstractAst":private]=>
    object(Youshido\GraphQL\Parser\Location)#905 (2) {
      ["line":"Youshido\GraphQL\Parser\Location":private]=>
      int(42)
      ["column":"Youshido\GraphQL\Parser\Location":private]=>
      int(49)
    }
  }
}
``

and like that after function is being called :

``
array(2) {
  [0]=>
  object(Youshido\GraphQL\Parser\Ast\Argument)#898 (3) {
    ["name":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    string(8) "location"
    ["value":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    array(2) {
      ["lat"]=>
      string(4) "51.5"
      ["lon"]=>
      string(1) "0"
    }
    ["location":"Youshido\GraphQL\Parser\Ast\AbstractAst":private]=>
    object(Youshido\GraphQL\Parser\Location)#901 (2) {
      ["line":"Youshido\GraphQL\Parser\Location":private]=>
      int(42)
      ["column":"Youshido\GraphQL\Parser\Location":private]=>
      int(14)
    }
  }
  [1]=>
  object(Youshido\GraphQL\Parser\Ast\Argument)#902 (3) {
    ["name":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    string(4) "unit"
    ["value":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    string(2) "mi"
    ["location":"Youshido\GraphQL\Parser\Ast\AbstractAst":private]=>
    object(Youshido\GraphQL\Parser\Location)#905 (2) {
      ["line":"Youshido\GraphQL\Parser\Location":private]=>
      int(42)
      ["column":"Youshido\GraphQL\Parser\Location":private]=>
      int(49)
    }
  }
}
``

Then is the second iteration before function is being called :

``
array(2) {
  [0]=>
  object(Youshido\GraphQL\Parser\Ast\Argument)#898 (3) {
    ["name":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    string(8) "location"
    ["value":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    array(2) {
      ["lat"]=>
      string(4) "51.5"
      ["lon"]=>
      string(1) "0"
    }
    ["location":"Youshido\GraphQL\Parser\Ast\AbstractAst":private]=>
    object(Youshido\GraphQL\Parser\Location)#901 (2) {
      ["line":"Youshido\GraphQL\Parser\Location":private]=>
      int(42)
      ["column":"Youshido\GraphQL\Parser\Location":private]=>
      int(14)
    }
  }
  [1]=>
  object(Youshido\GraphQL\Parser\Ast\Argument)#902 (3) {
    ["name":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    string(4) "unit"
    ["value":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    string(2) "mi"
    ["location":"Youshido\GraphQL\Parser\Ast\AbstractAst":private]=>
    object(Youshido\GraphQL\Parser\Location)#905 (2) {
      ["line":"Youshido\GraphQL\Parser\Location":private]=>
      int(42)
      ["column":"Youshido\GraphQL\Parser\Location":private]=>
      int(49)
    }
  }
}
``

and after :

``
array(2) {
  [0]=>
  object(Youshido\GraphQL\Parser\Ast\Argument)#898 (3) {
    ["name":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    string(8) "location"
    ["value":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    array(0) {
    }
    ["location":"Youshido\GraphQL\Parser\Ast\AbstractAst":private]=>
    object(Youshido\GraphQL\Parser\Location)#901 (2) {
      ["line":"Youshido\GraphQL\Parser\Location":private]=>
      int(42)
      ["column":"Youshido\GraphQL\Parser\Location":private]=>
      int(14)
    }
  }
  [1]=>
  object(Youshido\GraphQL\Parser\Ast\Argument)#902 (3) {
    ["name":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    string(4) "unit"
    ["value":"Youshido\GraphQL\Parser\Ast\Argument":private]=>
    string(2) "mi"
    ["location":"Youshido\GraphQL\Parser\Ast\AbstractAst":private]=>
    object(Youshido\GraphQL\Parser\Location)#905 (2) {
      ["line":"Youshido\GraphQL\Parser\Location":private]=>
      int(42)
      ["column":"Youshido\GraphQL\Parser\Location":private]=>
      int(49)
    }
  }
}
``

So as u see in last example value is empty array.

I will let u know if I have fix for that.

**Comment by m-naw** [comment]
I created PR with fix #113 

I would need to cover it by tests. Can I follow style from Tests/Issues directory and create Issue99Test and Issue99Schema?

**Comment by viniychuk** [comment]
@m-naw Absolutely, thank you, later we'll have it merged into general set of tests though.

**Comment by viniychuk** [comment]
btw, in your sample there is a typo and when I removed it it just worked for me....:

`agrX` and `argX`

**Comment by m-naw** [comment]
@viniychuk sorry I didnt test this example, wanted to mock my situation by custom code.

Anyway I updated it and fixed typos, checked and now you will have an error when u use example from the first comment.

What I changed is CustomField has to to return CustomType not StringType.

**Comment by m-naw** [comment]
@viniychuk ok I added test. PR is ready for CR.

**Comment by viniychuk** [comment]
@m-naw thanks again, it works now.
